serious_squad/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    url('login', auth_views.LoginView.as_view(template_name="user_login.html"), name="user_login"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('serious_squad_app.urls')),
    path('verification/', include('verify_email.urls')),
]

serious_squad_app/models.py
from django.db import models
from notifications.base.models import AbstractNotification
from django.contrib.auth.models import User

class Notification(AbstractNotification):
    class Meta(AbstractNotification.Meta):
        abstract = False
        app_label = 'serious_squad_app'

def user_directory_path(instance, filename):
    return '{0}/{1}'.format(instance.user.username, filename)

class Data(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255, blank=False, default='')
    filename = models.CharField(max_length=255, blank=True)
    data = models.FileField(upload_to=user_directory_path)
    description = models.CharField(max_length=255, blank=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    uploaded_at_1 = models.DateTimeField(auto_now_add=True)
    expires_on = models.DateTimeField(null=True)
    key = models.CharField(max_length=255, blank=True)
    inappropiate_flag = models.BooleanField(blank = False, default=False)
    universal = models.CharField(max_length=255, blank=False, default='No')
    specific_user = models.CharField(max_length=255,null=True)

    def delete(self, *args, **kwargs):
        self.data.delete()
        super().delete(*args, **kwargs)

class Request(models.Model):
    data = models.ForeignKey(Data, on_delete=models.CASCADE)
    data_owner = models.IntegerField(blank=False)
    data_consumer = models.IntegerField(blank=False)
    data_approve_status = models.BooleanField(blank=False, default=False)
    requested_at = models.DateTimeField(auto_now_add=True)

class UserActivity(models.Model):
    activity = models.CharField(max_length=255)
    time = models.DateTimeField(auto_now_add=True)
    time_1 = models.DateTimeField(auto_now_add=True)

class ReportFlag(models.Model):
    data = models.ForeignKey(Data, on_delete=models.CASCADE)
    report_count = models.IntegerField(blank=True, null=True)
    report_comment = models.CharField(max_length=2000, blank=False)
    reported_by = models.CharField(max_length=2000, blank=True)
    last_reported = models.DateTimeField(auto_now_add=True)

serious_squad_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator
from .models import *

def validate_email(value):
    if User.objects.filter(email = value).exists():
        raise ValidationError((f"{value} already exists !!!."),params = {'value':value})

def validate_user(value):
    if not User.objects.filter(username = value).exists():
        raise ValidationError((f"Can't share file with '{value}'. User '{value}' does not exist !!!."),params = {'value':value})

def validate_file_size(value):
    filesize= value.size
    
    if filesize > 15728640:
        raise ValidationError("The maximum file size that can be uploaded is 15MB")
    else:
        return value

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, required=True, validators = [validate_email])

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

class DataForm(forms.ModelForm):
    specific_user = forms.CharField(validators = [validate_user], required = False)
    data = forms.FileField(validators = [validate_file_size, FileExtensionValidator( ['doc','docx','pdf','txt','odt','rtf','wpd','ods','xls','xlsm','xlsx','pptx','ppt','pps','odp','key','csv','dat','db','dbf','log','sql','tmp','bak','tar','bin','7z','rar','tar.gz','bz','zip','mp3','mpa','ogg','wav','wma','vcf','pst','ost','bmp','gif','ico','jpeg','jpg','png','psd'] )])
    class Meta:
        model = Data
        fields = ('title','data','description','expires_on','universal','specific_user',)

class ReportForm(forms.ModelForm):
    class Meta:
        model = ReportFlag
        fields = '__all__'
        exclude = ('reported_by','report_count')

templates/admin_dashboard.html
{% extends 'base.html' %}
{% block content %}

<style type="text/css">
  .card:hover{
     transform: scale(1.05);
  box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06);
}
</style>
<div class="container">
<br>

<div class="row">
      <div class="col-12 mt-3 mb-1">
        <h4 class="text-uppercase text-muted">Administrator Dashboard</h4>
      </div>
    </div>
		<br>

		<div class="row">
      <div class="col-xl-6 col-sm-6 col-12">
        <div class="card shadow-sm btn">
          <a class="text-info" style="text-decoration:none;" href="{% url 'manage_user' %}">
          <div class="card-content">
            <div class="card-body">
              <div class="media d-flex">
                <div class="align-self-center">
									<i class="bi-person float-left text-info display-3"></i>
                </div>
                <div class="media-body text-right">
                  <h4>Manage Users</h4>
                  <p>Activate, Deactivate or Remove Users</p>
                </div>
              </div>
            </div>
          </div>
          </a>
        </div>
      </div>
      <div class="col-xl-6 col-sm-6 col-12">
        <div class="card shadow-sm btn">
          <a class="text-info" style="text-decoration:none;" href="{% url 'list_user_activity' %}">
          <div class="card-content">
            <div class="card-body">
              <div class="media d-flex">
                <div class="align-self-center">
                  <i class="bi-activity float-left text-info display-3"></i>
                </div>
                <div class="media-body text-right">
                  <h4>Monitor User Activity</h4>
                  <p>User Activities</p>
                </div>
              </div>
            </div>
          </div>
          </a>
        </div>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-xl-6 col-sm-6 col-12">
        <div class="card shadow-sm btn">
          <a class="text-info" style="text-decoration:none;" href="{% url 'list_user_data' %}">
          <div class="card-content">
            <div class="card-body">
              <div class="media d-flex">
                <div class="align-self-center">
                  <i class="bi-files float-left text-info display-3"></i>
                </div>
                <div class="media-body text-right">
                  <h4>User Files</h4>
                  <p>User Uploaded Files</p>
                </div>
              </div>
            </div>
          </div>
          </a>
        </div>
      </div>
      <div class="col-xl-6 col-sm-6 col-12">
        <div class="card shadow-sm btn">
          <a class="text-info" style="text-decoration:none;" href="{% url 'flagged_data' %}">
          <div class="card-content">
            <div class="card-body">
              <div class="media d-flex">
                <div class="align-self-center">
                  <i class="bi-file-earmark-check float-left text-info display-3"></i>
                </div>
                <div class="media-body text-right">
                  <h4>Moderate Flagged Files</h4>
                  <p>Review Files</p>
                </div>
              </div>
            </div>
          </div>
          </a>
        </div>
      </div>
    </div>
		<br>
</div>
<br>
<br>
<br>
{% endblock %}

templates/base.html
{% load static %}
{% load notifications_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>{% block title %}IBADS{% endblock %}</title>
<link rel="shortcut icon" type="image/png" href="{% static 'serious_squad_app/image/favicon.ico' %}"/>
<link href="{% static 'serious_squad_app/css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'serious_squad_app/css/font-awesome.min.css' %}" rel="stylesheet">
<link href="{% static 'serious_squad_app/js/bootstrap.min.js' %}">
<link href="{% static 'serious_squad_app/js/bootstrap.js' %}">
<link href="{% static 'serious_squad_app/js/bootstrap.bundle.min.js' %}">
<link href="{% static 'serious_squad_app/js/bootstrap.bundle.js' %}">
<link href="{% static 'serious_squad_app/js/jquery.min.js' %}">
<script src="{% static 'serious_squad_app/js/jquery.min.js' %}"></script>
<link href="{% static 'serious_squad_app/js/popper.min.js' %}">
<link href="{% static 'serious_squad_app/icons/font/bootstrap-icons.css' %}" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"></script>
<script src="https://code.jquery.com/jquery-3.6.0.js"></script>
<script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>

<style type="text/css">
  .card-header{z-index: 1000;}
</style>
</head>

<body class="bg-light">
<div>
    <nav class="navbar navbar-expand-md navbar-light sticky-top bg-info shadow">
      <div class="container">
        <h4><a href="{% url 'home' %}" class="navbar-brand text-light"><img src="{% static 'serious_squad_app/image/logo3.png' %}" class = "img-responsive" width = "32%">
        &nbsp;&nbsp;&nbsp;&nbsp;Identity-Based Authenticated Data Sharing</a></h4>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
          
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="dropdown ">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuLink" data-toggle="dropdown" aria-expanded="false">
                <i class="fa fa-bell" style="font-size:23px"></i>
                <span class="badge bg-danger circle position-absolute" style="font-size:10px;">{% live_notify_badge %}</span>
              </button>
              <div class="dropdown-menu w-60 p-3" aria-labelledby="dropdownMenu2">
                {% for notification in user.notifications.unread %}
    	           <div class="text-center">
                   {% if notification.actor != None %}
                    <b class="text-muted">{{notification.verb}}</b>
                    <br>
                     {{notification.description}}
                   </a>
    		         </div>
    		           <div class="dropdown-divider"></div>
                   {% endif %}
                   {% empty %}
                   <div class="text-center">
                    <h7><b>No notification</b></h7>
                  </div>
    	              {% endfor %}
                    {% if user.notifications.unread|length >= 1 %}
                    <div class="text-center">
                    <button class="dropdown-item" type="button" ><a style="font-size:15px;" href="{% url 'clear_notification' %}">Clear Notification</a></button>
                  </div>
                    {% endif %}
                </div>
        		</div>
        </div>
          &nbsp;&nbsp;
          
          {% if user.is_authenticated %}
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ml-auto">
                <div class="dropdown">
  					<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    				Hi {{ user.username }}!
  					</button>
  					       <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                      <a class="dropdown-item" href="{% url 'change_password' %}">Change Password</a>
   					          <a class="dropdown-item" href="{% url 'user_logout' %}">Logout</a>
  					        </div>
				        </div>
			      </div>
          </div>
          {% endif %}
        </div>
    </nav>
</div>

{% block content %}
{% endblock %}

<!-- Footer -->
<footer class="page-footer font-small bg-info blue fixed-bottom shadow-lg">
  <!-- Copyright -->
  <div class="footer-copyright text-center py-3 text-light">© 2022 Copyright:
    <a href="" class="text-white">Ganpat University | IBADS By Group-01 </a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->
</body>
</html>

templates/change_password.html
{% extends "base.html" %}

{% block content %}

<div class="card-header sticky-top bg-muted">
<div class="container">
<a href="{% url 'home' %}" class="btn bg-info text-white">&larr; Back</a>
</div>
</div>
<br>
<div class="container">
	{% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <div class="alert alert-primary">
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
        </div>
    </ul>
  {% endif %}
	<div class="row">
		<div class="col-lg-5 mx-auto">
			<div class="card card-signin my-4 shadow-sm" >
				<div class="card-body">
					<div class="card-title bg-white">
						<h4 class="text-info text-center">Change password for your account</h4>
					</div>
					<br>
					<form class="form-signin" method="post">
						{% csrf_token %}

						<div class="form-group">
						<label for="id_old_password" class="control-label text-secondary"><b>Old Password</b></label>
						<input class="form-control" type="password" name="old_password" placeholder="Old Password" autofocus required id="id_old_password">
						</div>

						<div class="form-group">
						<label for="id_new_password1" class="control-label text-secondary"><b>New Password</b></label>
						<input class="form-control" type="password" name="new_password1" placeholder="New Password" required id="new_password1">
						</div>

						<div class="form-group">
						<label for="id_new_password2" class="control-label text-secondary"><b>New Password Confirmation</b></label>
						<input class="form-control" type="password" name="new_password2" placeholder="New Password Confirmation" required id="new_password2">
						</div>
						{% if form.errors %}
							{% for field in form %}
								{% for error in field.errors %}
									<div class="alert alert-danger">
										<strong>{{ field.label_tag }}{{ error|escape }}</strong>
									</div>
								{% endfor %}
							{% endfor %}
						{% endif %}

							<div class="form-group">
									<div class="controls">
											<button class="btn btn-md btn-primary btn-block bg-info" type="submit">Submit</button>
									</div>
							</div>

					</form>
					<br>
			</div>
		</div>
	</div>
</div>
</div>

{% endblock %}

templates/index.html
{% extends 'base_index.html' %}
{% block content %}

<style type="text/css">
  .card:hover{
     transform: scale(1.05);
  box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06);}
</style>
<div class="container">
<br>
<br>
<br>
<br>
<br>
    <div class="row">
      <div class="col-sm-12 text-center align-self-center">
            <p class="text-info" style="letter-spacing: 7px;font-size: 20px;"><b>WELCOME TO IBADS</b></p>
            <h1 class="text-secondary" style="font-size: 64px;"><b>Share Data Securely</b></h1>
            <br><br>
              <a href="{% url 'user_login' %}" class="btn btn-lg btn-outline-info rounded-pill mr-2"><b>&nbsp; Sign In &nbsp;</b></a>
              <a href="{% url 'user_signup' %}" class="btn btn-lg btn-outline-info rounded-pill"><b>&nbsp; Sign Up &nbsp;</b></a> &nbsp;
              <a href="{% url 'about' %}" class="btn btn-lg btn-outline-info rounded-pill"><b>&nbsp; About &nbsp;</b></a>
      </div>
    </div>
		<br>
</div>
<br>
<br>
<br>
{% endblock %}

templates/list_data.html
{% extends "base.html" %}
{% block content %}

<div class="card-header sticky-top bg-light">
<div class="container">
<a href="{% url 'home' %}" class="btn bg-info text-white">&larr; Back</a>
</div>
</div>
<br>
<div class="container">
  <div class="card">
    <div class="card-body bg-white">
      <h5 class="text-center text-secondary"><b>Search Data</b></h5>
      <br>
  <form method="get">
        <div class="row">
          <div class="col">
            <div class="form-group">
          <label for="id_title" class="text-secondary"><b>Title</b></label>
          <input class="form-control" id="id_title" type="text" name="title" placeholder="Title">
        </div>
      </div>
      <div class="col">
        <div class="form-group">
          <label for="id_filename" class="text-secondary"><b>Filename</b></label>
          <input class="form-control" id="id_filename" type="text" name="filename" placeholder="Filename">
        </div>
      </div>
      <div class="col">
        <div class="form-group">
          <label for="id_universal" class="text-secondary"><b>Data Type</b></label>
          <select class="form-control" id="id_universal" name="universal">
            <option value="" selected>Any</option>
            <option value="Yes">Public</option>
            <option value="No">Private</option>
            </select>
        </div>
      </div>
      </div>
      <div class="row">
          <div class="col">
            <div class="form-group">
          <label for="id_description" class="text-secondary"><b>Description</b></label>
          <input class="form-control" id="id_description" type="text" name="description" placeholder="Description">
        </div>
        </div>
        <div class="col">
            <div class="form-group">
          <label for="id_user" class="text-secondary"><b>Data Owner</b></label>
          <select class="form-control" id="id_user" name="user">
            <option value="" selected>Any</option>
            {% for i in users %}
            {% if i.username != 'admin' %}
            <option value={{i.id}}>{{i.username}}</option>
            {% endif %}
            {% endfor %}
            </select>
        </div>
      </div>
      
    </div>
      <br>
      <button class="btn btn-info btn-md align-middle" type="submit">Search</button>
  </form>
</div>
</div>
<br>
	<table class="table table-bordered bg-white">
    <thead>
      <tr>
        <th class="text-center align-middle">Title</th>
        <th class="text-center align-middle">Filename</th>
        <th class="text-center align-middle">Description</th>
        <th class="text-center align-middle">Data Type</th>
        <th class="text-center align-middle">Data Owner</th>
        <th class="text-center align-middle">Expiration date</th>
        <th class="text-center align-middle">Action</th>
      </tr>
    </thead>
  <tbody>
    {% for data in filter.qs %}
      <tr>
        <td>{{ data.title }}</td>
        <td>{{ data.filename }}</td>
        <td>{{ data.description }}</td>
        {% if data.universal == 'Yes' %}
        <td>Public</td>
        {% else %}
        <td>Private</td>
        {% endif %}
        <td>{{ data.user }}</td>

        <td>{{ data.expires_on }}</td>
        <td>
          {% if data.universal == 'Yes' or data.specific_user == user.username %}
          <a href="/download_data/{{data.data}}"><div class="btn btn-info">Download</div></a>
          {% else %}
          <a href="#"><div class="btn btn-info">&nbsp;&nbsp;Request&nbsp;&nbsp;</div></a>
          {% endif %}
        </td>
      </tr>
      {% empty %}
        <tr>
          <td colspan="7">No data</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <br><br><br>
</div>
{% endblock %}

templates/list_user_data.html
{% extends "base.html" %}
{% block content %}

<div class="card-header sticky-top bg-light">
<div class="container">
<a href="{% url 'home' %}" class="btn bg-info text-white">&larr; Back</a>
</div>
</div>
<br>
<div class="container">
  <div class="card">
    <div class="card-body bg-white">
      <h5 class="text-center text-secondary"><b>Search Files</b></h5>
      <br>
  <form method="get">
        <div class="row">
          <div class="col">
            <div class="form-group">
          <label for="id_title" class="text-secondary"><b>Title</b></label>
          <input class="form-control" id="id_title" type="text" name="title" placeholder="Title">
        </div>
      </div>
      <div class="col">
        <div class="form-group">
          <label for="id_filename" class="text-secondary"><b>Filename</b></label>
          <input class="form-control" id="id_filename" type="text" name="filename" placeholder="Filename">
        </div>
      </div>
      <div class="col">
            <div class="form-group">
          <label for="id_description" class="text-secondary"><b>Description</b></label>
          <input class="form-control" id="id_description" type="text" name="description" placeholder="Description">
        </div>
        </div>
      </div>
      <div class="row">
          <div class="col">
        <div class="form-group">
          <label for="id_universal" class="text-secondary"><b>File Type</b></label>
          <select class="form-control" id="id_universal" name="universal">
            <option value="" selected>Any</option>
            <option value="Yes">Public</option>
            <option value="No">Private</option>
            </select>
        </div>
      </div>
        <div class="col">
            <div class="form-group">
          <label for="id_user" class="text-secondary"><b>File Owner</b></label>
          <select class="form-control" id="id_user" name="user">
            <option value="" selected>Any</option>
            {% for i in users %}
            {% if i.username != 'admin' %}
            <option value={{i.id}}>{{i.username}}</option>
            {% endif %}
            {% endfor %}
            </select>
        </div>
      </div>
      <div class="col">
        <div class="form-group">
          <label for="id_uploaded_at" class="text-secondary"><b>Upload date from</b></label>
          <input class="form-control" id="id_uploaded_at" type="date" name="uploaded_at">
        </div>
      </div>
      <div class="col">
        <div class="form-group">
          <label for="id_uploaded_at" class="text-secondary"><b>Upload date to</b></label>
          <input class="form-control" id="id_uploaded_at" type="date" name="uploaded_at_1">
        </div>
      </div>
      
    </div>
      <br>
      <button class="btn btn-info btn-md align-middle" type="submit">Search</button>
  </form>
</div>
</div>
<br>
	<table class="table table-bordered bg-white table-hover">
    <thead class="thead-light">
      <tr>
        <th class="text-center align-middle">Title</th>
        <th class="text-center align-middle">Filename</th>
        <th class="text-center align-middle">Description</th>
        <th class="text-center align-middle">File Type</th>
        <th class="text-center align-middle">File Owner</th>
        <th class="text-center align-middle">Upload date</th>
        <th class="text-center align-middle">Expiration date</th>
        <th class="text-center align-middle">Action</th>
      </tr>
    </thead>
  <tbody>
    {% for data in filter %}
      <tr>
        <td>{{ data.title }}</td>
        <td>{{ data.filename }}</td>
        <td>{{ data.description }}</td>
        {% if data.universal == 'Yes' %}
        <td>Public</td>
        {% else %}
        <td>Private</td>
        {% endif %}
        <td>{{ data.user }}</td>
        <td>{{ data.uploaded_at.date }}</td>
        <td>{{ data.expires_on.date }}</td>
        <td class="text-center">
          <a href="/download_data/{{data.data}}"><div class="btn btn-info">Download</div></a>
          <a href="{% url 'delete_data' data.id %}"><div class="btn btn-danger" onclick="return confirm('Are you sure?');">Delete</div></a>
        </td>
      </tr>
      {% empty %}
        <tr>
          <td colspan="8">No data</td>
        </tr>
      {% endfor %}
      
    </tbody>
  </table>
  <br><br><br>
</div>
{% endblock %}

templates/upload_data.html
{% extends 'base.html' %}

{% block content %}

<div class="card-header sticky-top">
<div class="container">
<a href="{% url 'home' %}" class="btn bg-info text-white">&larr; Back</a>
</div>
</div>

<div class="container">

<script>
  function access(that) {
    if (that.id == "id_universal_specific") {
        document.getElementById("id_specific_user").required = true;
        document.getElementById("div_id_specific_user").style.display = "block";
    } 
    else {
        document.getElementById("id_specific_user").required = false;
        document.getElementById("div_id_specific_user").style.display = "none";
    }
}
</script>

{% if messages %}
  <br>
    <ul class="messages">
        {% for message in messages %}
        <div class="alert alert-success">
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
        </div>
    </ul>
  {% endif %}

<div class="row">
    <div class="col-lg-7 mx-auto">
      <div class="card card-signin my-4 shadow-sm" >
        <div class="card-body">
          <div class="card-title bg-white">
            <h4 class="text-info text-center">UPLOAD</h4>
          </div>
          <br>
 <form method="post" enctype="multipart/form-data">
    
    {% csrf_token %}
    <div class="row">
      <div class="col">
    <div id="div_id_title" class="form-group text-secondary">
      <div class="">
        <label class="control-label text-secondary" for="title"><b>*Title</b></label>
        <input type="text" name="title" maxlength="255" class="textinput textInput form-control" required id="id_title" placeholder="*Title">
      </div>
    </div>
    <div id="div_id_data" class="form-group text-secondary">
      <div class="">
        <label class="control-label text-secondary" for="data"><b>*Upload</b></label>
        <input type="file" name="data" class="clearablefileinput form-control-file" required id="id_data">
      </div>
    </div>
    <div id="div_id_expires_on" class="form-group text-secondary">
      <div class="">
        <label class="control-label text-secondary" for="expires_on"><b>*Expires on</b></label>
        <input type="datetime-local" min="{{date}}" name="expires_on" maxlength="255" class="textinput textInput form-control" required id="id_expires_on" placeholder="*expires_on">
      </div>
    </div>
  </div>
  <div class="col">
    <div id="div_id_description" class="form-group text-secondary">
      <div class="">
        <label class="control-label text-secondary" for="description"><b>Description</b></label>
        <textarea rows="2" name="description" maxlength="255" class="textinput textInput form-control" id="id_description" placeholder="Description"></textarea>
      </div>
    </div>
    <div id="div_id_universal" class="form-group text-secondary">
      <label class="control-label text-secondary" for="universal"><b>Who can access this file?</b></label>
      <br>
      <div class="form-check form-check-inline">
        <input type="radio" name="universal" maxlength="255" class="form-check-input" id="id_universal_yes" value="Yes" onchange="access(this);">
        <label class="form-check-label text-secondary" for="universal_yes">Anyone</label>
      </div>
      <div class="form-check form-check-inline">
        <input type="radio" name="universal" maxlength="255" class="form-check-input" id="id_universal_no" value="No" checked onchange="access(this);">
        <label class="form-check-label text-secondary" for="universal_no">Users with permission</label>
      </div>
      <div class="form-check form-check-inline">
        <input type="radio" name="universal" maxlength="255" class="form-check-input" id="id_universal_specific" value="No" onchange="access(this);">
        <label class="form-check-label text-secondary" for="universal_specific">Specific User</label>
      </div>
    </div>
    <div id="div_id_specific_user" class="form-group text-secondary" style="display: none;">
        <input type="text" name="specific_user" maxlength="255" class="textinput textInput form-control" id="id_specific_user" placeholder="Enter user's username">
    </div>
  </div>
  </div>
  {% if form.errors %}
                {% for field in form %}
                  {% for error in field.errors %}
                    <div class="alert alert-danger">
                      <strong>{{ error|escape }}</strong>
                    </div>
                  {% endfor %}
                {% endfor %}
              {% endif %}
  <p class="text-danger">* Indicates required field</p>
    <button class="btn btn-md btn-primary bg-info btn-block" type="submit">Upload</button>

  </form>
  <br>
        </div>
      </div>
    </div>
  </div>
<br>
<br>
</div>

{% endblock %}